version: "3"
services: 
  rabbit:
    image: rabbitmq:3.8-management
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment: 
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 123456
  mongo:
    image: mongo:4.4
    container_name: "mongodb"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456 
      MONGO_INITDB_DATABASE: test
